### ISSUE TITLE
Poor performance on custom pointcloud: how can I tune it?

### ISSUE THREAD

**Issue by GabijaBern** [ecker-lab/TreeLearn#4]
Hello, I have tried to test TreeLearn with custom data and I am not getting good performance... Could you advice me how I could tune the algorithm? I have tried to use 24mx24m tile, having around 10mln points. I have changed the configuration like this: 1. change the path to pointcloud 2. outer_edge: 0 3. inner_edge: 2 4. outer_remove: 0. I get something that looks like out of bounds or something error as the tree id is a very big number:

![Screenshot from 2024-01-09 13-36-15](https://github.com/ecker-lab/TreeLearn/assets/37048728/bf0a725a-814d-4f08-aea5-8d8333ab37de)

**Comment by jonaden94** [comment]
Dear GabijaBern,

the configuration arguments outer_edge and inner_edge do not refer to the extensions of the input point cloud. Rather, the input point cloud is partitioned into smaller tiles, each of which has an edge length of outer_edge + inner_edge. Pointwise predictions are then made for all points within the inner part of the tiles. All inner predictions are then stitched together to obtain segmentation results on the input point cloud. You should leave the inner_edge and outer_edge arguments as they are since the model has been trained with tiles of this size. Setting the argument outer_remove=0 leads to predictions being made for the entire input point cloud. Although you can do that, be aware that predictions at the edge will not have the expected segmentation  quality since the network needs context for prediction. It is recommended to retain outer_remove=13.5 and supply a larger input point cloud. For example, if you want to segment a 24x24 meters cloud, you should supply a 51x51 meters cloud. The buffer will automatically be removed and the output will be 24x24 meters. An initial point cloud size of 24x24 meters might be too small to produce adequate segmentation results.

I hope this helps. If there are any further issues, feel free to reach out to us.

**Comment by GabijaBern** [comment]
Thank you, I have listened to your advice and I am getting results such as:
![Screenshot from 2024-01-15 08-01-35](https://github.com/ecker-lab/TreeLearn/assets/37048728/02dd7cc0-5fc9-4496-85da-0b63f1186a5a)
![Screenshot from 2024-01-15 08-04-49](https://github.com/ecker-lab/TreeLearn/assets/37048728/c61ee6e0-d893-4a84-ab87-13d5c3f23774)


How can I tune it to perform better?

**Comment by jonaden94** [comment]
Without having the point cloud at hand, it is hard to determine what the reason for the suboptimal performance is. If it is possible to share the data with me via mail, I'll be happy to take a look at it.

**Comment by GabijaBern** [comment]
Hey, what would be your email address?

**Comment by jonaden94** [comment]
jonathan.henrich@uni-goettingen.de
