### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by Cocktail-salad** [ecker-lab/TreeLearn#5]
Dear ecker-lab
When I run this line of instruction:python tools/training/train.py --config configs/training/train.yaml
the error is reported as follows:
Traceback (most recent call last):
  File "/home/jjgw/The project/TreeLearn-main/tools/training/train.py", line 158, in <module>
    main()
  File "/home/jjgw/The project/TreeLearn-main/tools/training/train.py", line 147, in main
    train(config, epoch, model, optimizer, scheduler, scaler, train_loader, logger, writer)
  File "/home/jjgw/The project/TreeLearn-main/tools/training/train.py", line 43, in train
    scaler.scale(loss).backward()
  File "/home/jjgw/anaconda3/envs/treelearn/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/jjgw/anaconda3/envs/treelearn/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 236.00 MiB (GPU 0; 15.70 GiB total capacity; 12.34 GiB already allocated; 208.19 MiB free; 13.58 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

But according to the paper's description, the GPU may be satisfied with as little as 9GB. Of course I admit that before this I was generating crops of 2500. my device is 4080 (16GB), which should be sufficient. So please, what should I do?
yours
JJGW

**Comment by JanvDelden** [comment]
Dear JJGW,
to reduce the memory requirement for training a model you can reduce the batch size set in the train.yaml file [here](https://github.com/ecker-lab/TreeLearn/blob/main/configs/training/train.yaml). Just set batch_size in line 12 to 1. The specification of 9 GB in the paper only applies to running the pipeline (inference) and not for training a new model. 
Otherwise, you can also reduce the size of the crops that are processed by the neural network. You could also do this by modifying the .yaml config files. But this might impact the capability of the neural network to locate the base of the tree since it needs to be within the crop to be located. So we would not recommend reducing the crop size as a first step.

Please let us know if this fixes your issues.

**Comment by JanvDelden** [comment]
On second thought, we noticed that batch_size set to 1 will cause problems with the batch norm layers. Thus, it would not work without modifying the network architecture. The other solution, to reduce the size of the crops is still valid.  For this, you have to modify the chunk_size argument for training in configs/data_gen/gen_train_data.yaml. For inference, the argument outer_edge in configs/_modular/sample_generation needs to be adapted accordingly. You can reduce the chunk size by reducing the values for these arguments.
